apiVersion: devops.example.com/v1
kind: MyResource
metadata:
  labels:
    app.kubernetes.io/name: k8s-custom-controller
    app.kubernetes.io/managed-by: kustomize
  name: myresource-sample
spec:
  # TODO(user): Add fields here
